### ISSUE TITLE
More details on installlation ...

### ISSUE THREAD

**Issue by bshor** [bonidier/synodlna-index#1]
I installed ipkg, then bash, then git, and then cloned the files.

Questions:

1) What directory should I clone it in? I used @tmp, hope that is ok.

2) Does this run automatically now, or do I need to reissue the command every once in a while (obviously that would defeat the point).

3) If the indexer is running in the background, how do I stop it if I need to?

4) I do get some errors when I list the shares: "./lib/synodlna/synodlna-shares.lib.sh: line 44: tr: command not found" before it goes on to list photo, video, audio. What is "tr"?

**Comment by bonidier** [comment]
Hi @bshor 

thanks for your feedback

1) there is no fixed destination for the script, you can put it anywhere, like ~/script/synodlna-index

2) actually if you want to automate indexation, you should put the command in the admin user crontab. I'll add it with an example  in the README.md

3) a command like this should work, but I'll improve the script to catch this

```
killall synodlna-reindex.sh
```

4) I think I'd missed some dependencies about IPKG in README file,
Try it : 

```
ipkg install coreutils
```

I'll give you a better answer about all this questions In few hours, when I'll be near my NAS

Thanks !

---

PS : don't use "@" in GitHub if the right part isn't a user
It will notify any user with that name about this ticket, and can says "why me ?"  ^_^

**Comment by bshor** [comment]
2) Ok, looking for an example, thanks. But I'm a little unclear -- is it running in the background, updating and reindexing when I say, upload a new photo or video? I'm a little unclear as to what "reindex now" means.

4) Ok installed coreutils. When I list shares it does list my shares correctly but I also get "tr: warning: an unescaped backslash at end of string is not portable
array_add: missing parameters"

Thanks...

**Comment by bonidier** [comment]
Hi bshor, 

about 2) : Its a good idea, not yet implemented, but possible !

about 4) :  since my last post I've made an update for DSM 5 shares detection compatibility and passed the "tr" command with an absolute path, /usr/bin/tr (native binary on my NAS)

If latest version can't fix the "tr" warning, I'll put some binaries path variables overridable in "config.sh" file ASAP

Thanks

**Comment by bshor** [comment]
2) Oh. That's what I thought this was for! Automatic reindexing. Can't I just clock "reindex" if I want in the control panel? What does this do that's different? I don't want to manually reindex ... I want the system to monitor when I upload new media files and have automatically added so I can see them with DLNA ....

4) I am running 4.2 ...

Thanks!

**Comment by bonidier** [comment]
Hi bshor,

about your 2) question, I've just pushed a second script for automatic indexing support, using inotify-tools, and a daemon service for it

the README is biggest, because of dependencies but I'll simplify install process shortly

thanks for your feedback
